language: php
php:
  - '7.0'

install:
  - composer install
  - npm install
  - node_modules/bower/bin/bower install
  - pip install numpy --user
  - pip install biom-format --user

services:
  - postgresql

addons:
  apt:
    packages:
    - python-h5py
    - python-numpy
    - python-scipy
  postgresql: "9.4"

before_script:
  - cp test/php/.travis.config.php test/php/config.php

script:
  - phpunit
  - npm test
