language: php
php:
  - '7.0'

install:
  - composer install
  - npm install
  - node_modules/bower/bin/bower install

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - cp test/.travis.parameters_test.yml app/config/parameters_test.yml

script:
  - phpunit
