language: php
php:
  - '5.6'

install:
  - composer install
  - npm install
  - node_modules/bower/bin/bower install

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - cp test/php/.travis.config.php test/php/config.php

script:
  - phpunit
  - npm test
