language: php
php:
  - '7.0'

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

install:
  - composer install
  - npm install
  - node_modules/bower/bin/bower install
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy biom-format

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - cp test/php/.travis.config.php test/php/config.php

script:
  - phpunit
  - npm test
