sudo: false
dist: trusty
language: php
php:
  - '7.0'

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes numpy scipy h5py
  - pip install biom-format --user
  - cp tests/.travis.parameters.yml app/config/parameters.yml
  - composer install
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - node_modules/bower/bin/bower install

services:
  - postgresql

addons:
  apt:
    packages:
      - python-h5py
  postgresql: "9.5"

before_script:
  - psql -c 'create database test;' -U postgres
  - cp tests/.travis.parameters_test.yml app/config/parameters_test.yml

script:
  - phpunit
  - gulp test
