language: php
php:
  - '5.6'

install:
  - composer install

services:
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  - cp test/php/.travis.config.php test/php/config.php
  - npm install
  - node_modules/bower/bin/bower install

script:
  - phpunit
  - grunt jasmine
