language: php
php:
  - '7.0'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-h5py

install:
  - composer install
  - npm install
  - node_modules/bower/bin/bower install
  - pip install numpy
  - pip install biom-format

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - cp test/php/.travis.config.php test/php/config.php

script:
  - phpunit
  - npm test
