app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

github_check:
    path: /login/check-github

github_login:
    path: /connect/github

google_login:
    path: /connect/google

google_check:
    path: /login/check-google

logout:
    path: /logout