# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.db:
        class: AppBundle\DB
        arguments: ['%dbversions%']
    app.api.listing.overview:
        class: AppBundle\API\Listing\Overview
        arguments: ['@app.db']
    app.api.listing.organisms:
            class: AppBundle\API\Listing\Organisms
            arguments: ['@app.db']