# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.orm:
        class: AppBundle\ORM
        arguments: [ "@doctrine" ]
    app.db:
        class: AppBundle\DB
        arguments: ['%dbversions%']
    app.api.webservice:
        class: AppBundle\API\Webservice
        arguments: ['@app.db']
    app.api.ormwebservice:
        class: AppBundle\API\ORMWebservice
        arguments: ['@app.orm']
    app.user.provider:
        class: AppBundle\User\FennecUserProvider