# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.orm:
        class: AppBundle\ORM
        arguments: [ '@doctrine' ]
    app.api.webservice:
        class: AppBundle\API\Webservice
        arguments: ['@app.orm','@security.token_storage']
    app.twig_provider.dbversion:
        class: AppBundle\Service\TwigProvider\DBVersion
        arguments: ['@twig', '%doctrine.default_connection%']
        tags: [{name: kernel.event_listener, event: kernel.request}]
    app.twig_provider.types:
        class: AppBundle\Service\TwigProvider\Types
        arguments: ['@twig']
        tags: [{name: kernel.event_listener, event: kernel.request}]
    app.form.registration:
        class: AppBundle\Form\RegistrationFormType
        tags: [{name: form.type, alias: app_user_registration }]
    app.fos_user.oauth_provider:
        # Change the class according to the location of the FOSUBUserProvider class
        class: AppBundle\Entity\FOSUBUserProvider
        arguments: ['@fos_user.user_manager.default', {github: github_id}]
#            # Inject as first argument the user_manager of FOSUserBundle
#            user_manager: "@fos_user.user_manager.default"
#            # An object/array with the registered Social Media from config.yml
#            user_response:
#                github: github_id